language: r

sudo: required

compiler:
  - g++

r_binary_packages
  - devtools
  - Rcpp
  - RcppEigen

r_packages:
  - assertive
  - covr

r_github_packages:
  - cdeterman/RViennaCL
  
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers libboost-program-options-dev
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so

after_success:
  - Rscript -e 'library(covr);coveralls()'

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
