matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8

#whitelist branches
branches:
  only:
    - master
    - macosx
    - develop

language: r

dist: trusty
sudo: required
group: edge
warnings_are_errors: false

compiler:
  - g++
  

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

r_binary_packages:
  - devtools
  - Rcpp
  - RcppEigen
  - roxygen2
  - stringi

r_packages:
  - assertive

r_github_packages:
  - cdeterman/RViennaCL
  - jimhester/covr
  
before_install:
  - if [ -n "$GH_TOKEN" ]; then git config --global github.accesstoken ${GH_TOKEN}; fi;
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main restricted"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - apt-get update || true
  - sudo apt-get install -qq -y --force-yes g++-4.8 cmake git libtool libhwloc-dev wget g++ pkg-config libpthread-stubs0-dev clang-3.8 lldb-3.8 libclang-3.8-dev
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
  - |
    git clone -b release_0_14 https://github.com/pocl/pocl.git pocl
    cd pocl
    mkdir build
    cd build
    cmake ..
    make
    sudo make install

after_success:
  - Rscript -e 'devtools::install();library(gpuR);library(methods);devtools::test()'
  - Rscript -e 'options(covr.gcov = "gcov-4.8");library(covr);coveralls(line_exclusions = "inst/include/CL/cl.hpp");codecov(line_exclusions = "inst/include/CL/cl.hpp")'

notifications:
  email:
    on_success: change
    on_failure: change
