language: r

sudo: required

compiler:
  - g++

r_packages:
  - assertive

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - BH
  - bigmemory.sri

r_github_packages:
  - kaneplusplus/bigmemory
  - cdeterman/bigalgebra

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx opencl-headers libboost-program-options-dev
  - cd ..
  - git clone http://github.com/arrayfire/clBLAS.git
  - cd clBLAS
  - mkdir -p build && cd build
  - cmake ../src -DCMAKE_BUILD_TYPE=Release
  - make && sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib64:${LD_LIBRARY_PATH}
  - export LD_RUN_PATH=/usr/local/lib64:${LD_RUN_PATH}
  - cd ${TRAVIS_BUILD_DIR}

notifications:
  email:
    on_success: change
    on_failure: change