
platform:
  - x86

shallow_clone: true

environment:
  global:
    OPENCL_REGISTRY: "https://www.khronos.org/registry/cl"
    OPENCL_LIB: "C:\\Windows\\System32"
    OPENCL_INC: "C:\\projects\\inc"
    R_CHECK_ARGS: "--no-multiarch"

# $ErrActionPreference = "Stop" when we tighten this up.
# DO NOT CHANGE the "init" and "install" sections below
# Download script file from GitHub
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: |
        $ErrorActionPreference = "Continue"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - ps: Bootstrap
  - echo Installing OpenCL
  - echo %OPENCL_LIB%
  - echo %OPENCL_INC%
  - ps: $opencl_registry = $env:OPENCL_REGISTRY
  - ps: cd ..
  # This downloads the source to the example/demo icd library
  - ps: wget $opencl_registry/specs/opencl-icd-1.2.11.0.tgz -OutFile opencl-icd-1.2.11.0.tgz
  - ps: 7z x opencl-icd-1.2.11.0.tgz
  - ps: 7z x opencl-icd-1.2.11.0.tar
  - ps: mv .\icd\* .
  # This downloads all the opencl header files
  # The cmake build files expect a directory called inc
  - ps: mkdir inc/CL
  - ps: wget $opencl_registry/api/1.2/ | select -ExpandProperty links | where {$_.href -like "*.h*"} | select -ExpandProperty outerText | foreach{ wget $opencl_registry/api/1.2/$_ -OutFile inc/CL/$_ }
  - cmd: build_using_cmake.bat  
  - ps: ls
  - ps: cd gpur
  - ps: ls

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
